class SurahInfo {
  final int number;
  final String nameAr;
  final String nameEn;
  final int totalVerses;

  const SurahInfo({
    required this.number,
    required this.nameAr,
    required this.nameEn,
    required this.totalVerses,
  });
}

class QuranData {
  static const List<SurahInfo> surahs = [
    SurahInfo(number: 1, nameAr: "الفاتحة", nameEn: "Al-Fatihah", totalVerses: 7),
    SurahInfo(number: 2, nameAr: "البقرة", nameEn: "Al-Baqarah", totalVerses: 286),
    SurahInfo(number: 3, nameAr: "آل عمران", nameEn: "Ali 'Imran", totalVerses: 200),
    SurahInfo(number: 4, nameAr: "النساء", nameEn: "An-Nisa", totalVerses: 176),
    SurahInfo(number: 5, nameAr: "المائدة", nameEn: "Al-Ma'idah", totalVerses: 120),
    SurahInfo(number: 6, nameAr: "الأنعام", nameEn: "Al-An'am", totalVerses: 165),
    SurahInfo(number: 7, nameAr: "الأعراف", nameEn: "Al-A'raf", totalVerses: 206),
    SurahInfo(number: 8, nameAr: "الأنفال", nameEn: "Al-Anfal", totalVerses: 75),
    SurahInfo(number: 9, nameAr: "التوبة", nameEn: "At-Tawbah", totalVerses: 129),
    SurahInfo(number: 10, nameAr: "يونس", nameEn: "Yunus", totalVerses: 109),
    SurahInfo(number: 11, nameAr: "هود", nameEn: "Hud", totalVerses: 123),
    SurahInfo(number: 12, nameAr: "يوسف", nameEn: "Yusuf", totalVerses: 111),
    SurahInfo(number: 13, nameAr: "الرعد", nameEn: "Ar-Ra'd", totalVerses: 43),
    SurahInfo(number: 14, nameAr: "إبراهيم", nameEn: "Ibrahim", totalVerses: 52),
    SurahInfo(number: 15, nameAr: "الحجر", nameEn: "Al-Hijr", totalVerses: 99),
    SurahInfo(number: 16, nameAr: "النحل", nameEn: "An-Nahl", totalVerses: 128),
    SurahInfo(number: 17, nameAr: "الإسراء", nameEn: "Al-Isra", totalVerses: 111),
    SurahInfo(number: 18, nameAr: "الكهف", nameEn: "Al-Kahf", totalVerses: 110),
    SurahInfo(number: 19, nameAr: "مريم", nameEn: "Maryam", totalVerses: 98),
    SurahInfo(number: 20, nameAr: "طه", nameEn: "Taha", totalVerses: 135),
    SurahInfo(number: 21, nameAr: "الأنبياء", nameEn: "Al-Anbiya", totalVerses: 112),
    SurahInfo(number: 22, nameAr: "الحج", nameEn: "Al-Hajj", totalVerses: 78),
    SurahInfo(number: 23, nameAr: "المؤمنون", nameEn: "Al-Mu'minun", totalVerses: 118),
    SurahInfo(number: 24, nameAr: "النور", nameEn: "An-Nur", totalVerses: 64),
    SurahInfo(number: 25, nameAr: "الفرقان", nameEn: "Al-Furqan", totalVerses: 77),
    SurahInfo(number: 26, nameAr: "الشعراء", nameEn: "Ash-Shu'ara", totalVerses: 227),
    SurahInfo(number: 27, nameAr: "النمل", nameEn: "An-Naml", totalVerses: 93),
    SurahInfo(number: 28, nameAr: "القصص", nameEn: "Al-Qasas", totalVerses: 88),
    SurahInfo(number: 29, nameAr: "العنكبوت", nameEn: "Al-'Ankabut", totalVerses: 69),
    SurahInfo(number: 30, nameAr: "الروم", nameEn: "Ar-Rum", totalVerses: 60),
    SurahInfo(number: 31, nameAr: "لقمان", nameEn: "Luqman", totalVerses: 34),
    SurahInfo(number: 32, nameAr: "السجدة", nameEn: "As-Sajdah", totalVerses: 30),
    SurahInfo(number: 33, nameAr: "الأحزاب", nameEn: "Al-Ahzab", totalVerses: 73),
    SurahInfo(number: 34, nameAr: "سبأ", nameEn: "Saba", totalVerses: 54),
    SurahInfo(number: 35, nameAr: "فاطر", nameEn: "Fatir", totalVerses: 45),
    SurahInfo(number: 36, nameAr: "يس", nameEn: "Ya-Sin", totalVerses: 83),
    SurahInfo(number: 37, nameAr: "الصافات", nameEn: "As-Saffat", totalVerses: 182),
    SurahInfo(number: 38, nameAr: "ص", nameEn: "Sad", totalVerses: 88),
    SurahInfo(number: 39, nameAr: "الزمر", nameEn: "Az-Zumar", totalVerses: 75),
    SurahInfo(number: 40, nameAr: "غافر", nameEn: "Ghafir", totalVerses: 85),
    SurahInfo(number: 41, nameAr: "فصلت", nameEn: "Fussilat", totalVerses: 54),
    SurahInfo(number: 42, nameAr: "الشورى", nameEn: "Ash-Shura", totalVerses: 53),
    SurahInfo(number: 43, nameAr: "الزخرف", nameEn: "Az-Zukhruf", totalVerses: 89),
    SurahInfo(number: 44, nameAr: "الدخان", nameEn: "Ad-Dukhan", totalVerses: 59),
    SurahInfo(number: 45, nameAr: "الجاثية", nameEn: "Al-Jathiyah", totalVerses: 37),
    SurahInfo(number: 46, nameAr: "الأحقاف", nameEn: "Al-Ahqaf", totalVerses: 35),
    SurahInfo(number: 47, nameAr: "محمد", nameEn: "Muhammad", totalVerses: 38),
    SurahInfo(number: 48, nameAr: "الفتح", nameEn: "Al-Fath", totalVerses: 29),
    SurahInfo(number: 49, nameAr: "الحجرات", nameEn: "Al-Hujurat", totalVerses: 18),
    SurahInfo(number: 50, nameAr: "ق", nameEn: "Qaf", totalVerses: 45),
    SurahInfo(number: 51, nameAr: "الذاريات", nameEn: "Adh-Dhariyat", totalVerses: 60),
    SurahInfo(number: 52, nameAr: "الطور", nameEn: "At-Tur", totalVerses: 49),
    SurahInfo(number: 53, nameAr: "النجم", nameEn: "An-Najm", totalVerses: 62),
    SurahInfo(number: 54, nameAr: "القمر", nameEn: "Al-Qamar", totalVerses: 55),
    SurahInfo(number: 55, nameAr: "الرحمن", nameEn: "Ar-Rahman", totalVerses: 78),
    SurahInfo(number: 56, nameAr: "الواقعة", nameEn: "Al-Waqi'ah", totalVerses: 96),
    SurahInfo(number: 57, nameAr: "الحديد", nameEn: "Al-Hadid", totalVerses: 29),
    SurahInfo(number: 58, nameAr: "المجادلة", nameEn: "Al-Mujadila", totalVerses: 22),
    SurahInfo(number: 59, nameAr: "الحشر", nameEn: "Al-Hashr", totalVerses: 24),
    SurahInfo(number: 60, nameAr: "الممتحنة", nameEn: "Al-Mumtahanah", totalVerses: 13),
    SurahInfo(number: 61, nameAr: "الصف", nameEn: "As-Saff", totalVerses: 14),
    SurahInfo(number: 62, nameAr: "الجمعة", nameEn: "Al-Jumu'ah", totalVerses: 11),
    SurahInfo(number: 63, nameAr: "المنافقون", nameEn: "Al-Munafiqun", totalVerses: 11),
    SurahInfo(number: 64, nameAr: "التغابن", nameEn: "At-Taghabun", totalVerses: 18),
    SurahInfo(number: 65, nameAr: "الطلاق", nameEn: "At-Talaq", totalVerses: 12),
    SurahInfo(number: 66, nameAr: "التحريم", nameEn: "At-Tahrim", totalVerses: 12),
    SurahInfo(number: 67, nameAr: "الملك", nameEn: "Al-Mulk", totalVerses: 30),
    SurahInfo(number: 68, nameAr: "القلم", nameEn: "Al-Qalam", totalVerses: 52),
    SurahInfo(number: 69, nameAr: "الحاقة", nameEn: "Al-Haqqah", totalVerses: 52),
    SurahInfo(number: 70, nameAr: "المعارج", nameEn: "Al-Ma'arij", totalVerses: 44),
    SurahInfo(number: 71, nameAr: "نوح", nameEn: "Nuh", totalVerses: 28),
    SurahInfo(number: 72, nameAr: "الجن", nameEn: "Al-Jinn", totalVerses: 28),
    SurahInfo(number: 73, nameAr: "المزمل", nameEn: "Al-Muzzammil", totalVerses: 20),
    SurahInfo(number: 74, nameAr: "المدثر", nameEn: "Al-Muddaththir", totalVerses: 56),
    SurahInfo(number: 75, nameAr: "القيامة", nameEn: "Al-Qiyamah", totalVerses: 40),
    SurahInfo(number: 76, nameAr: "الإنسان", nameEn: "Al-Insan", totalVerses: 31),
    SurahInfo(number: 77, nameAr: "المرسلات", nameEn: "Al-Mursalat", totalVerses: 50),
    SurahInfo(number: 78, nameAr: "النبأ", nameEn: "An-Naba", totalVerses: 40),
    SurahInfo(number: 79, nameAr: "النازعات", nameEn: "An-Nazi'at", totalVerses: 46),
    SurahInfo(number: 80, nameAr: "عبس", nameEn: "'Abasa", totalVerses: 42),
    SurahInfo(number: 81, nameAr: "التكوير", nameEn: "At-Takwir", totalVerses: 29),
    SurahInfo(number: 82, nameAr: "الانفطار", nameEn: "Al-Infitar", totalVerses: 19),
    SurahInfo(number: 83, nameAr: "المطففين", nameEn: "Al-Mutaffifin", totalVerses: 36),
    SurahInfo(number: 84, nameAr: "الانشقاق", nameEn: "Al-Inshiqaq", totalVerses: 25),
    SurahInfo(number: 85, nameAr: "البروج", nameEn: "Al-Buruj", totalVerses: 22),
    SurahInfo(number: 86, nameAr: "الطارق", nameEn: "At-Tariq", totalVerses: 17),
    SurahInfo(number: 87, nameAr: "الأعلى", nameEn: "Al-A'la", totalVerses: 19),
    SurahInfo(number: 88, nameAr: "الغاشية", nameEn: "Al-Ghashiyah", totalVerses: 26),
    SurahInfo(number: 89, nameAr: "الفجر", nameEn: "Al-Fajr", totalVerses: 30),
    SurahInfo(number: 90, nameAr: "البلد", nameEn: "Al-Balad", totalVerses: 20),
    SurahInfo(number: 91, nameAr: "الشمس", nameEn: "Ash-Shams", totalVerses: 15),
    SurahInfo(number: 92, nameAr: "الليل", nameEn: "Al-Layl", totalVerses: 21),
    SurahInfo(number: 93, nameAr: "الضحى", nameEn: "Ad-Duha", totalVerses: 11),
    SurahInfo(number: 94, nameAr: "الشرح", nameEn: "Ash-Sharh", totalVerses: 8),
    SurahInfo(number: 95, nameAr: "التين", nameEn: "At-Tin", totalVerses: 8),
    SurahInfo(number: 96, nameAr: "العلق", nameEn: "Al-'Alaq", totalVerses: 19),
    SurahInfo(number: 97, nameAr: "القدر", nameEn: "Al-Qadr", totalVerses: 5),
    SurahInfo(number: 98, nameAr: "البينة", nameEn: "Al-Bayyinah", totalVerses: 8),
    SurahInfo(number: 99, nameAr: "الزلزلة", nameEn: "Az-Zalzalah", totalVerses: 8),
    SurahInfo(number: 100, nameAr: "العاديات", nameEn: "Al-'Adiyat", totalVerses: 11),
    SurahInfo(number: 101, nameAr: "القارعة", nameEn: "Al-Qari'ah", totalVerses: 11),
    SurahInfo(number: 102, nameAr: "التكاثر", nameEn: "At-Takathur", totalVerses: 8),
    SurahInfo(number: 103, nameAr: "العصر", nameEn: "Al-'Asr", totalVerses: 3),
    SurahInfo(number: 104, nameAr: "الهمزة", nameEn: "Al-Humazah", totalVerses: 9),
    SurahInfo(number: 105, nameAr: "الفيل", nameEn: "Al-Fil", totalVerses: 5),
    SurahInfo(number: 106, nameAr: "قريش", nameEn: "Quraysh", totalVerses: 4),
    SurahInfo(number: 107, nameAr: "الماعون", nameEn: "Al-Ma'un", totalVerses: 7),
    SurahInfo(number: 108, nameAr: "الكوثر", nameEn: "Al-Kawthar", totalVerses: 3),
    SurahInfo(number: 109, nameAr: "الكافرون", nameEn: "Al-Kafirun", totalVerses: 6),
    SurahInfo(number: 110, nameAr: "النصر", nameEn: "An-Nasr", totalVerses: 3),
    SurahInfo(number: 111, nameAr: "المسد", nameEn: "Al-Masad", totalVerses: 5),
    SurahInfo(number: 112, nameAr: "الإخلاص", nameEn: "Al-Ikhlas", totalVerses: 4),
    SurahInfo(number: 113, nameAr: "الفلق", nameEn: "Al-Falaq", totalVerses: 5),
    SurahInfo(number: 114, nameAr: "الناس", nameEn: "An-Nas", totalVerses: 6),
  ];

  static SurahInfo getByNumber(int num) {
    return surahs.firstWhere(
      (s) => s.number == num,
      orElse: () => surahs.first,
    );
  }

  static SurahInfo getByNameAr(String name) {
    return surahs.firstWhere(
      (s) => s.nameAr == name,
      orElse: () => surahs.first,
    );
  }
}
